config/routes.rb
Rails.application.routes.draw do
  
  # get 'post_list', to: 'posts#list'
  # get 'new_post', to: 'posts#new'
  # post 'create_post', to: 'posts#create'
  # get 'current_post/:id', to: 'posts#current'
  # get 'edit_post/:id', to: 'posts#edit'
  # post 'posts/:id', to: 'posts#update'
  # post 'update_post/:id', to: 'posts#update'

  # get 'user_list', to: 'users#list'
  # get 'new_user', to: 'users#new'
  # post 'create_user', to: 'users#create'
  # get 'current_user/:id', to: 'users#current'
  # get 'edit_user/:id', to: 'users#edit'
  # post 'update_user/:id', to: 'users#update'

  resources :posts do
    resource :comments, only: [:create]
  end
  resources :users
  resources :categories
  resources :votes

  get '/log_in', to: 'sessions#new'
  post '/log_in', to: 'sessions#create'
  post '/log_out', to: 'sessions#destroy', as: :log_out




end

app/models/badge.rb
class Badge < ActiveRecord::Base

  has_many :user_badges
  has_many :users, through: :user_badges


end

app/models/category.rb
class Category < ActiveRecord::Base

  validates :name, presence: true, length: { minimum: 4 }

  has_many :post_categories
  has_many :posts, through: :post_categories


end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

  validates :content, length: { minimum: 10 }

  has_many :votes, as: :voteable

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, presence: true, length: { minimum: 4 }
  validates :content, presence: true, length: { minimum: 10, maximum: 500 }

  has_many :comments
  belongs_to :user

  has_many :post_categories
  has_many :categories, through: :post_categories

  has_many :votes, as: :voteable

  before_create :calculate_slug

  BAD_CHARACTERS = /[ :\-\.]/
  IRR_CHARACTERS = /[@?$%&^*!]/
  
  def calculate_slug

    self.slug = title.downcase
      .gsub(BAD_CHARACTERS, '_')
      .gsub(IRR_CHARACTERS, '')
      .gsub('__', '_')

  end


end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base

  belongs_to :post
  belongs_to :category

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, length: { minimum: 3}
  validates :age, numericality: { only_integer: true }
  validates :email, uniqueness: true

  has_many :posts
  has_many :comments

  has_many :user_badges
  has_many :badges, through: :user_badges

  has_secure_password validations: false



end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base

  belongs_to :badge 
  belongs_to :user

end

app/models/vote.rb
class Vote < ActiveRecord::Base

    belongs_to :voteable, polymorphic: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    helper_method :current_user, :logged_in?

    def current_user
      if session[:user_id]
        User.find(session[:user_id]) 
      end
    end

    def logged_in?
      current_user.present?
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index

    @categories = Category.all

  end

  def new

    @category = Category.new

  end

  def create

    attrs = params.require(:category).permit(:name)
    @category = Category.new(attrs)

    if @category.save
      redirect_to categories_path   
    else
      render :new
    end

  end

  def show

    @category = Category.find(params[:id])

  end

  def edit

    @category = Category.find(params[:id])

  end

  def update

    @category = Category.find(params[:id])
    attrs = params.require(:category).permit(:name)
    @category.update(attrs)

    redirect_to categories_path
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create

    @post = Post.find(params[:post_id])
    attrs = params.require(:comment).permit(:content).merge(post_id: @post.id)
		# @comment = @post.comments.build(attrs)
		@comment = Comment.new(attrs)

    if @comment.save
			redirect_to post_path(@post)
		else
			render 'posts/show'
		end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController	

	def index
		@posts = Post
      .order(created_at: :desc)
      .offset((page - 1) * per_page)
      .limit(per_page)
      .includes(:categories, :votes)

    @total_pages = (Post.count / per_page.to_f).ceil
  end
    
  def create

		attrs = params.require(:post).permit(:title, :content, category_ids: [])
		@post = Post.new(attrs)
    #Calculate Slug
    #Add to post before saving
    #@post.slug = @post.calculate_slug
# require 'pry'; binding.pry
    if @post.save
      redirect_to post_path(@post)		
    else
      render :new
    end

	end

  def new
    
    @post = Post.new

  end

	def show

		@post = Post.find_by(id: params[:id]) || Post.find_by(slug: params[:id])

    if @post
      @comments = @post.comments.includes(:votes)
      @comment = @post.comments.build

    else
      render 'shared/not_found', status: 404
	  end
	end

	def edit

		@post = Post.find(params[:id])
		
	end

	def update

		@post = Post.find(params[:id])
		attrs = params.require(:post).permit(:title, :content)

		if @post.update(attrs)
      redirect_to post_path(@post)
    else
      render :edit
    end
			
	end

  private

    def per_page
      5
    end

    def page
      return 1 if !params[:page]

      params[:page].to_i
    end    

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create

    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      redirect_to log_in_path
    end
    
  end

  def destroy

    session[:user_id] = nil
    redirect_to posts_path

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User
      .order(created_at: :desc)
      .offset((page - 1) * per_page)
      .limit(per_page)
      .includes(:badges)

    @total_users = (User.count / per_page.to_f).ceil
	end

	def new

    @user = User.new
		
	end

	def create

		attrs = params.require(:user).permit(:name, :email, :age)
		@user = User.new(attrs)

		if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
    
	end

	def show
		@current_user = User.find(params[:id])
	end

	def edit

		@user = User.find(params[:id])
		
	end

	def update

		@user = User.find(params[:id])
		attrs = params.require(:user).permit(:name, :email, :age)

		if @user.update(attrs)
      redirect_to user_path(@user)
    else
      render :edit
    end
	end

  private

    def per_page
      5
    end

    def page
      return 1 if !params[:page]

      params[:page].to_i
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController	

  def create

    attrs = params.permit(:voteable_type, :voteable_id)
    Vote.new(attrs).save
    
    redirect_to :back

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<h1>Create A Category</h1>

<% if category.errors %>
	<ul>
		<% category.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<% end %>
	</ul>

<% end %>

<%= form_for category do |f| %>
	<%= f.label :name %>
	<br>
	<%= f.text_field :name %>
	<br>
	<%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h1>Category Index</h1>

<% @categories.each do |category| %>
	<p><%= category.name %></p>
	<hr>
<% end %>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p><%= @category.name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id='navbar'>
	<h1>
	<%= link_to 'Log Out', log_out_path, method: 'post' %>
	</h1>
</div>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% if post.errors %>
	<ul>
		<% post.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<% end %>
	</ul>

<% end %>

<%= form_for post do |f| %>
	<%= f.label :title %>
	<br>
	<%= f.text_field :title %>
	<br>
	<%= f.label :content %>
	<br>
	<%= f.text_area :content, size: "60x12" %>
	<br>
	<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |cat|%>
    	<%= cat.label {cat.check_box() + cat.text } %>
    <%end%>
    <br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<% (1..@total_pages).each do |page| %>
  <%= link_to("Page #{page} | ", posts_path(page: page)) %>
<% end %>

<% @posts.each do |post| %>
	<h1><%= post.id %></h1>
	TOTAL VOTES: <%= post.votes.size %>
	<br>
	<p><%= post.content %></p>
	<% post.categories.each do |category| %>
	<ul>    
    <li><%= category.name %></li>
    </ul>
	<% end %>
	<br>
    <br>
    <% if logged_in? %>

    	<%= link_to('Vote', votes_path(voteable_type: 'Post', voteable_id: post.id, user_id: 1), method: 'post') %>

    <% end %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% if @comment.errors %>
	<ul>
		<% @comment.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<% end %>
	</ul>

<% end %>


<h1><%= @post.title %></h1>
<br>
<% if logged_in? %>
<%= link_to(
		'Vote',
		votes_path(
			voteable_type:'Post',
			voteable_id: @post.id
		), 
			method: 'post' 
		)
			%>
<% end %>
TOTAL VOTES: <%= @post.votes.size %>
<p><%= @post.content %></p>

<% if logged_in? %>
<%= form_for([@post, @comment]) do |f| %>
	<p>
		<%= f.label :content %>
		<br>
		<%= f.text_area :content %>
	</p>	

	<p>
		<%= f.submit %>
	</p>
<% end %>
<% end %>


<h2>Comments</h2>

<% @comments.each do |comment| %>
	<hr>
	<% if logged_in? %>
	<%= link_to(
		'Vote',
		votes_path(
			voteable_type:'Comment',
			voteable_id: comment.id
		), 
			method: 'post' 
		)
			%>
	<% end %>
	<br>
	<br>
	TOTAL VOTES: <%= comment.votes.size %>
	<br>
	<div><%= comment.content %></div>
<% end %>

app/views/shared/not_found.html.erb
<h1>Not found</h1>

app/views/users/_form.html.erb
<% if user.errors %>
	<ul>
		<% user.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<% end %>
	</ul>

<% end %>



<%= form_for user do |f| %>
	<%= f.label :name %>
	<br>
	<%= f.text_field :name %>
	<br>
	<%= f.label :email %>
	<br>
	<%= f.text_field :email %>
	<br>
	<%= f.label :age %>
	<br>
	<%= f.text_field :age %>
	<br>
	<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% (1..@total_users).each do |page| %>
  <%= link_to("Page #{page} | ", users_path(page: page)) %>
<% end %>


<% @users.each do |user| %>
	<h1><%= user.name %></h1>
	<p><%= user.email %></p>
	<p><%= user.age %></p>
<% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p><%= @current_user.name %></p>	
<p><%= @current_user.email %></p>
<p><%= @current_user.age %></p>

<h2>Posts</h2>

<% @current_user.posts.each do |post| %>
	<hr>
	<h4><%= post.title %></h4>
	<br>
	<div><%= post.content %></div>
<% end %>